image: node:20

stages:
  - test
  - lint
  - deploy

run_tests:
  stage: test
  script:
    - npm ci
    - npm test
  only:
    - main

lint_code:
  stage: lint
  script:
    - npm ci
    - npm run lint
  only:
    - main
  needs:
    - run_tests

deploy_to_firebase:
  stage: deploy
  script:
    - npm install -g firebase-tools
    - firebase deploy --token "$FIREBASE_DEPLOY_TOKEN" --project software-project-1dv613
  only:
    - main
  needs:
    - lint_code